import ast
from pathlib import Path

import pytest

from scripts.fetch_skill_source import fetch_source, git, RUNTIME_SCRIPTS


def commit_files(repository, files):
    for name, content in files.items():
        path = repository / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    git(repository, "add", ".")
    git(repository, "-c", "user.name=Test", "-c", "user.email=test@example.invalid",
        "commit", "-m", "fixture")
    return git(repository, "rev-parse", "HEAD")


def test_partial_checkout_excludes_unneeded_blobs_and_updates_same_version(tmp_path):
    remote = tmp_path / "remote"
    remote.mkdir()
    git(remote, "init", "-b", "main")
    git(remote, "config", "uploadpack.allowFilter", "true")
    included = {"image2editable/cli.py": "new runtime", "scripts/text_detect.py": "ocr",
                "scripts/worker_resources.py": "worker", "pyproject.toml": "version=0.3.0",
                "README_EN.md": "metadata", "LICENSE": "license",
                "constraints/runtime.txt": "dependencies", ".gitignore": "build/\n*.egg-info/\n"}
    excluded = {"benchmarks/corpus/sample.png": "fixture " * 10000,
                "tests/test_runtime.py": "test", "docs/images/demo.png": "demo",
                "scripts/release_benchmark.py": "benchmark runner",
                "scripts/generate_benchmark_corpus.py": "generator",
                ".github/workflows/ci.yml": "ci", "skills/other/SKILL.md": "other skill",
                "CHANGELOG.md": "history"}
    first = commit_files(remote, {**included, **excluded})
    checkout = tmp_path / "runtime"
    remote_url = remote.as_posix()
    assert fetch_source(checkout, remote_url) == first
    assert all((checkout / name).is_file() for name in included)
    assert all(not (checkout / name).exists() for name in excluded)
    assert git(checkout, "config", "--get", "remote.origin.partialclonefilter") == "blob:none"
    # Enumerate local objects without triggering lazy fetching of missing blobs.
    local_objects = set(git(checkout, "cat-file", "--batch-all-objects", "--batch-check=%(objectname)").splitlines())
    for name in excluded:
        assert git(remote, "rev-parse", f"HEAD:{name}") not in local_objects
    second = commit_files(remote, {"image2editable/cli.py": "updated runtime, same version"})
    (checkout / "build").mkdir()
    (checkout / "build/package.py").write_text("generated by pip")
    assert fetch_source(checkout, remote_url) == second
    assert (checkout / "image2editable/cli.py").read_text() == "updated runtime, same version"
    (checkout / "image2editable/cli.py").write_text("user edits")
    with pytest.raises(ValueError, match="Preserve local changes"):
        fetch_source(checkout, remote_url)
    assert (checkout / "image2editable/cli.py").read_text() == "user edits"


def test_existing_unmanaged_directory_is_not_modified(tmp_path):
    path = tmp_path / "source"
    path.mkdir()
    (path / "important.txt").write_text("keep")
    with pytest.raises(ValueError, match="managed Git checkout"):
        fetch_source(path)
    assert (path / "important.txt").read_text() == "keep"


def test_initial_skill_fetch_and_readme_commands_skip_other_repository_blobs(tmp_path):
    remote = tmp_path / "remote"
    remote.mkdir()
    git(remote, "init", "-b", "main")
    git(remote, "config", "uploadpack.allowFilter", "true")
    selected = {"skills/image-to-ppt/SKILL.md": "ppt",
                "skills/image-to-ppt/scripts/tool.py": "tool"}
    excluded = {"skills/image-to-psd/SKILL.md": "psd",
                "benchmarks/corpus/sample.png": "sample" * 1000,
                "image2editable/cli.py": "runtime", "README.md": "root readme"}
    commit_files(remote, {**selected, **excluded})
    helper_checkout = tmp_path / "helper"
    fetch_source(helper_checkout, remote.as_posix(), skill="image-to-ppt")
    cli_checkout = tmp_path / "cli"
    git(tmp_path, "clone", "--depth", "1", "--filter=blob:none", "--no-checkout",
        "--no-local", remote.as_posix(), str(cli_checkout))
    git(cli_checkout, "sparse-checkout", "set", "--no-cone", "/skills/image-to-ppt/")
    git(cli_checkout, "checkout")
    for checkout in (helper_checkout, cli_checkout):
        assert all((checkout / name).is_file() for name in selected)
        assert all(not (checkout / name).exists() for name in excluded)
        objects = set(git(checkout, "cat-file", "--batch-all-objects", "--batch-check=%(objectname)").splitlines())
        assert all(git(remote, "rev-parse", f"HEAD:{name}") not in objects for name in excluded)


def test_runtime_script_allowlist_covers_imports_and_subprocess_modules():
    root = Path(__file__).resolve().parents[1]
    selected = set(RUNTIME_SCRIPTS)
    paths = [*root.joinpath("image2editable").glob("*.py"), root / "image_to_ppt.py",
             root / "image_to_psd.py", *(root / "scripts" / name for name in selected if name.endswith(".py"))]
    for path in paths:
        for node in ast.walk(ast.parse(path.read_text(encoding="utf-8"))):
            modules = []
            if isinstance(node, ast.ImportFrom) and node.module:
                modules.append(node.module)
                if node.module == "scripts":
                    modules.extend("scripts." + alias.name for alias in node.names)
            elif isinstance(node, ast.Import):
                modules.extend(alias.name for alias in node.names)
            elif isinstance(node, ast.Constant) and isinstance(node.value, str):
                if node.value.startswith("scripts.") and " " not in node.value:
                    modules.append(node.value)
            for module in modules:
                if module.startswith("scripts."):
                    filename = module.split(".")[1] + ".py"
                    if (root / "scripts" / filename).is_file():
                        assert filename in selected, (path.name, module)
